# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Home', url: 'index.html'}
- {name: 'Codes', path: 'menu', url: 'codes.html'}
- {name: 'CV', path: 'menu', url: 'cv.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/muhrin'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/martin-uhrin-6ab4718/'}
- {icon: 'envelope', link: 'mailto:martin@digitalbaker.net'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

#related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
